name: Run Docker Tests
on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Running Unit Tests
        run: |
          docker compose run test 

