name: Push Docker Image
on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Setup
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build & push
        uses: docker/build-push-action@v6
        with: 
          push: true
          tags: |
            dunaalsulaiman/typescript-app:latest
            dunaalsulaiman/typescript-app:${{ github.sha }}